### ISSUE TITLE
breaks mediawiki's update.php

### ISSUE THREAD

**Issue by cariaso** [cmln/mw-bootstrap#4]
see context at
https://phabricator.wikimedia.org/T181719

recent changes to
localBasePath
such as in
https://github.com/cmln/mw-bootstrap/commit/fb5f98e90bf55c5f90e6e695b2a6c56bd88854b2
seem likely to be the source of the trouble

**Comment by cariaso** [comment]
I see the same message when running
php generateSitemap.php   
as well

**Comment by s7eph4n** [comment]
I think this is a duplicate of #3

**Comment by s7eph4n** [comment]
Fixed in 2b5f026
